server:
  port: 8888

logging:
  path: logs
  file: mylog.log


spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.9:3306/course?characterEncoding=UTF8
    username: root
    password:

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
