server:
  port: 8888

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.9:3306/course
    username: root
    password:

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/mysql.xml